"""update document schema

Revision ID: 15ec61f1b71c
Revises: 1b9252ae01f9
Create Date: 2026-07-30 14:52:38.631535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ec61f1b71c'
down_revision: Union[str, Sequence[str], None] = '1b9252ae01f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('documents', 'stored_filename')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
